USE [master]
GO

/* MSSQLServer Management studio'da oluþturduðum LogoDB isimli veritabanýnýn scripti aþaðýdaki gibidir.*/
CREATE DATABASE [LogoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LogoDB', FILENAME = N'E:\MSSQL2019Developer\MSSQL15.SQLDEVELOPER\MSSQL\DATA\LogoDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LogoDB_log', FILENAME = N'E:\MSSQL2019Developer\MSSQL15.SQLDEVELOPER\MSSQL\DATA\LogoDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LogoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LogoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LogoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LogoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LogoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LogoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LogoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LogoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LogoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LogoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LogoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LogoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LogoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LogoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LogoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LogoDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LogoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LogoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LogoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LogoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LogoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LogoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LogoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LogoDB] SET RECOVERY FULL 
GO

ALTER DATABASE [LogoDB] SET  MULTI_USER 
GO

ALTER DATABASE [LogoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LogoDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LogoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LogoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LogoDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LogoDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LogoDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LogoDB] SET  READ_WRITE 
GO


